### ISSUE TITLE
Job data when Bot doesn't send anything

### ISSUE THREAD

**Issue by ryanstgermaine** [bcjobs/analytics-dashboard#10]
Botcode isn't able to send us data for the next two days. They are in Chennai and there has been massive flooding. If you look at today's analytics report, it show zero new jobs and zero open jobs.

When Bot doesn't send us data, can we use the previous days data and then update when we new information? This has happened a few times and I'd prefer never to see no data there.

**Comment by johnnyoshika** [comment]
Moved here: https://github.com/bcjobs/analytics/issues/36
