### ISSUE TITLE
Normalization rules aren't working.

### ISSUE THREAD

**Issue by ryanstgermaine** [bcjobs/analytics-dashboard#14]
The normalization rules I created don't seem to be working. I created the rules in the screenshot below a few days ago and they aren't showing in today's data.

![rules](https://cloud.githubusercontent.com/assets/6778782/11732521/de527344-9f59-11e5-8d3b-653fb00aa804.png)

**Comment by johnnyoshika** [comment]
@ryanstgermaine, can you please provide an example data that was missed by the normalization rule?

**Comment by ma-gu** [comment]
@johnnyoshika, could you please provide the latest database backup for this task?

**Comment by johnnyoshika** [comment]
@ma-gu: sent via Skype.

**Comment by ryanstgermaine** [comment]
One example where the normalization rules aren't working is Sr. Software Developer should map to Senior Software Developer and it doesn't.

From what I can tell though, none of the rules are working.
