### ISSUE TITLE
I can create two normalization rules for the same title, skill or company

### ISSUE THREAD

**Issue by ryanstgermaine** [bcjobs/analytics-dashboard#15]
Hey Guys,

I accidentally created two different rules for the same job title making me realize we need to not allow that. For example, I initially created a rule to map "Back-End Developer (Ruby on Rails)" to "Ruby Developer". Later, I created another rule to map the same title of "Back-End Developer (Ruby on Rails)" to "Ruby on Rails Developer" and it allowed me to do that.

Can we put a check in place to make sure we can't do that? Also, if I have already created a rule for a keyword, skill or company, can we make it so that it is no longer included in the auto-complete dropdown when I type in the "Terms" box?

**Comment by johnnyoshika** [comment]
Add `unassigned=true` param to `search` endpoint which will exclude terms already used in rules.

Limit results to 20 entries.
