### ISSUE TITLE
Charts are broken

### ISSUE THREAD

**Issue by ryanstgermaine** [bcjobs/analytics-dashboard#16]
The current date always drops to zero even though there are jobs.

![chart_1](https://cloud.githubusercontent.com/assets/6778782/11733825/619b8194-9f66-11e5-9926-2709a23e3f22.png)

The weekly charts always show the charts from the previous day no matter what you select in the date picker.

![weekly_charts](https://cloud.githubusercontent.com/assets/6778782/11733827/632faf1c-9f66-11e5-92b5-83744909ee34.png)

**Comment by jsedlacek** [comment]
@ryanstgermaine The current date does not drop to zero - the y axis is not zero based. See chart legend on left.

The charts were not updated correctly when changing dates, this has been fixed now.
