### ISSUE TITLE
Send include param to /api/v1.0/search

### ISSUE THREAD

**Issue by johnnyoshika** [bcjobs/analytics-dashboard#19]
When sending GET requests to /api/v1.0/search, please also send this query string parameter:

`unassigned=true`

Ryan would like to see autocomplete results for only those rules that haven't yet been created, so we enhanced the API to pay attention to this query string.

**Comment by ma-gu** [comment]
We can skip this parameter on GET, cause I made it optional with ```unassigned=true``` value by default. So we really need it in query string only we want to pass ```false```.

**Comment by johnnyoshika** [comment]
@ma-gu: Now that I think about it, I think the terminology and the way we use it is confusing.  What do you think about changing it to this?

parameter: `assigned`
default: `bool? assigned = null`

if `assigned == null`, ignore filter.
if `assigned == true`, return only the ones that are assigned.
if `assigned == false`, return only the ones that are not assigned.  I will ask Jakub to send `assigned=false`

Related issue: https://github.com/bcjobs/analytics/issues/64

**Comment by jsedlacek** [comment]
@johnnyoshika @ma-gu I am holding this until we decide on the api. Please let me know when it's ready.

**Comment by johnnyoshika** [comment]
@jsedlacek: Yes, please wait until we solidify the API.  Thanks!

**Comment by johnnyoshika** [comment]
We've changed the API signature for better clarify.

Parameter name: `include`.

Available options (not case sensitive):
- all (default)
- used
- notUsed

Example: `/api/v1.0/search?ruleType=Job%20Title&q=Software&include=notUsed`

Both production and my dev server have been updated with these changs.  @jsedlacek, I think it's ready for your implementation.
