### ISSUE TITLE
Consume /api/v1.0/reports/range

### ISSUE THREAD

**Issue by johnnyoshika** [bcjobs/analytics-dashboard#20]
When the page loads, please call this endpoint to get the date range for the datepicker:

`/api/v1.0/reports/range`

Sample response:

```
{"startsAt":"2015-09-01T00:00:00","endsAt":"2015-12-14T00:00:00"}
```

Please note that this endpoint has been updated and may now return a 404:

`/api/v1.0/reports/outline?at=2015-12-13`

```
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8

{"message":"No data for the selected date.","code":"NotFound"}
```

Please handle this 404 and show the error message to the user.

Related issue:
https://github.com/bcjobs/analytics/issues/36#issuecomment-162926517

**Comment by jsedlacek** [comment]
@johnnyoshika Is this ready for me to work on it? I see that you assigned it to yourself.

**Comment by johnnyoshika** [comment]
@jsedlacek: yes, it's ready now.  Both production and my dev server have been updated.

To simulate 404 from `/api/v1.0/reports/outline`, you can pass an out of range parameter (e.g. `/api/v1.0/reports/outline?at=2015-08-30`).

**Comment by johnnyoshika** [comment]
@jsedlacek: the API (both my dev and production) have been updated.  You can now deploy this branch:

https://github.com/bcjobs/analytics-dashboard/commit/e38b193c6c209062ba8d991095fad51177482bfa

Thank you for your patience.

**Comment by johnnyoshika** [comment]
Here is a sample response:

```
{"startsAt":"2015-09-01","endsAt":"2015-12-14"}
```

We have removed the time part.
