### ISSUE TITLE
GET /api/v1.0/jobs/csv won't proxy

### ISSUE THREAD

**Issue by johnnyoshika** [bcjobs/analytics-dashboard#24]
@jsedlacek, I added dedupe csv download/upload features here:

http://localhost:4200/admin/dedupe

I don't know why, but I can't get this GET request to proxy to API:

/api/v1.0/jobs/csv

The PUT request proxies properly, but when it comes to GET, ember server returns index.html.

**Comment by johnnyoshika** [comment]
@jsedlacek: interesting.  What was preventing the proxy from working before?  Was it the request header of `Accept: text/html`?

**Comment by jsedlacek** [comment]
Yes, the ember-cli built-in proxy works only for `Accept: text/html`.

**Comment by johnnyoshika** [comment]
You mean works only for `Accept: application/json`?  :-)

**Comment by jsedlacek** [comment]
Sorry, I meant proxy does work for everything, but `Accept: text/html`.
