### ISSUE TITLE
Code review: dedupe csv upload/download

### ISSUE THREAD

**Issue by johnnyoshika** [bcjobs/analytics-dashboard#25]
A quick code review on the dedupe CSV upload/download would be appreciated.  Both upload and download are implemented inside a single template and controller.  It seems like maybe this controller/template combo are doing too much.  Would you recommend splitting this into 2 parts?  And if so, how?

Relevant commits:

https://github.com/bcjobs/analytics-dashboard/commit/868a8325f4650655c45f41e78d6477307f2e92bd
https://github.com/bcjobs/analytics-dashboard/commit/17eb14c8ffdb3ff81e7bbe9b68d7a0f06dfa527e

Thanks!

**Comment by jsedlacek** [comment]
@johnnyoshika I have split the code into two components. See referenced commits above.

**Comment by johnnyoshika** [comment]
@jsedlacek: fantastic, thank you!  It looks like we need to use components for these scenarios.
