### ISSUE TITLE
Migrate all legacy error handing to new ember-notify

### ISSUE THREAD

**Issue by johnnyoshika** [bcjobs/analytics-dashboard#46]
Let's migrate all legacy error handling to use our new ember-notify.  Example:

https://github.com/bcjobs/analytics-dashboard/blob/dev/app/authentication/password/route.js#L22,L24
https://github.com/bcjobs/analytics-dashboard/blob/dev/app/authentication/password/template.hbs#L14,L16

**Comment by LoganHollins** [comment]
@johnnyoshika Should i update info boxes as well? Example:

https://github.com/bcjobs/analytics-dashboard/blob/master/app/authentication/reset-password/route.js#L22
https://github.com/bcjobs/analytics-dashboard/blob/master/app/authentication/reset-password/template.hbs#L21,L23

Also I think we should move the notification to the top of the screen so it can be noticed, they give us some [custom css](https://github.com/aexmachina/ember-notify/blob/master/examples/custom-position-animations.css) to do so.

![image](https://cloud.githubusercontent.com/assets/6888104/13366900/13a0b77e-dc93-11e5-8496-368c669af7e9.png)
