### ISSUE TITLE
Analytics Bug

### ISSUE THREAD

**Issue by ryanstgermaine** [bcjobs/analytics-dashboard#57]
The IT Report show no data for selected date - http://analytics.bcjobs.ca/it-jobs

**Comment by ma-gu** [comment]
@johnnyoshika: Could you please provide the latest database backup and report generation log for investigating this issue?

**Comment by johnnyoshika** [comment]
@ma-gu: I will send it to you via Skype shortly.   Thanks!

**Comment by ma-gu** [comment]
@johnnyoshika: Interesting bug. It had occurred occasionally with the following message in Report.log:

`There is already an open DataReader associated with this Command which must be closed first.`  

which means that building report failed for IT type. Here's the line which throws exception: https://github.com/bcjobs/analytics/blob/master/BCJobs.Analytics.Reports/DbAsyncEnumerable.cs#L33

So, I have done:
1. Fired building with the next API call: http://analytics.bcjobs.ca/api/v1.0/reports/build?from=2016-02-29&to=2016-02-29
2. Wrap DataReader access in `using`: https://github.com/bcjobs/analytics/blob/fix-open-datareader-while-reportbuilding/BCJobs.Analytics.Reports/DbAsyncEnumerable.cs#L32

I'm not 100% sure, but it looks like that `using` resolved an issue. At least I was unable to reproduce this bug with this modification.

**Comment by johnnyoshika** [comment]
@ma-gu: very interesting.  Were you able to reproduce the bug before you made the fix?

I saw that you submitted a PR for Dmitry.  I'm curious to hear his opinion.

**Comment by ma-gu** [comment]
@johnnyoshika: Yes, I was able, but it was reproduced occasionally, from time to time, not with every firing. The same behavior you can see in Report log: sometimes we can see this message (about 'already an open DataReader'), sometimes it's absent. This bug was introduced with adding DbAsyncEnumerable.cs to our codebase.

**Comment by johnnyoshika** [comment]
@ma-gu: Sounds very promising.  Thank you!
