### ISSUE TITLE
Top 10 candidates in our database

### ISSUE THREAD

**Issue by ryanstgermaine** [bcjobs/analytics-dashboard#58]
Create a section with the the resume search where employers can go to view the "Top ten candidates" they are shown after they publish a job. This should be a section we can link to and email to the employer to entice them to come back to the site.

**Comment by ryanstgermaine** [comment]
@johnnyoshika is there a way to move this to jobcentre? Totally put in the wrong place. 

Is this just a UI/design issue that we can get Michelle on or does it require work from you?

**Comment by johnnyoshika** [comment]
@ryanstgermaine: you'll need to close this issue and re-create it in the proper repo.  Once you do, I'll add additional comments/questions there.
