### ISSUE TITLE
Subreport clickable target - visual indicator

### ISSUE THREAD

**Issue by johnnyoshika** [bcjobs/analytics-dashboard#63]
Please add a visual indicator on hover to the subreport clickable text (e.g. change colour or underline or something else).

![image](https://cloud.githubusercontent.com/assets/504505/14567948/6ade10a8-02eb-11e6-86ff-cc665670759a.png)

**Comment by lysodesigns** [comment]
Addressed this here: https://github.com/bcjobs/analytics-dashboard/pull/74
Let me know what you think @johnnyoshika
