### ISSUE TITLE
Loading state for subreport

### ISSUE THREAD

**Issue by johnnyoshika** [bcjobs/analytics-dashboard#64]
Please create a loading state for subreports so that while subreports are loading, a user sees some sort of 'loading progress' indicator (e.g. a spinner).  This is especially important if the data is not in the cache, as it can take a long time for the subreports to load.

**Comment by LoganHollins** [comment]
@lysodesigns I have implemented the logic for the spinner, would you be able to add some styles to make it easier to see with the background.

The spinner for the subreport is [here](https://github.com/bcjobs/analytics-dashboard/blob/608285d9ae404f8a4b9b72a35e9ba3c0172828af/app/components/bcic-subreport/template.hbs#L35-L36) if you want to make any changes to that.

I have added 2 second delay to the subreports for the mock server, so you should be able to see the spinner.

**Comment by LoganHollins** [comment]
@lysodesigns I should also mention that the branch is `subreport-spinner`
