### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by ryanstgermaine** [bcjobs/analytics-dashboard#7]
When creating a new rule or searching for an existing rule, the text box should start auto-populating based on what's in the database. For example, if I start typing Sr. in our "Terms" or "Replace" box it should automatically show me "Sr. Software Developer" if it's in our database.

**Comment by ryanstgermaine** [comment]
@jsedlacek @johnnyoshika  Can we add autocomplete when searching existing rules as well?

**Comment by jsedlacek** [comment]
@ryanstgermaine I have deployed to to http://analytics.bcjobs.ca/

Please let me know how it works for you.
