### ISSUE TITLE
Titles for reports

### ISSUE THREAD

**Issue by johnnyoshika** [bcjobs/analytics-dashboard#89]
# Trend Report

Trend reports are missing titles, so it's hard to know what's being reported.  Example:
### Software Jobs Report

![image](https://cloud.githubusercontent.com/assets/504505/17601302/4489df30-5fbc-11e6-83a8-1c00a71b6e62.png)
### IT Jobs Report

![image](https://cloud.githubusercontent.com/assets/504505/17601321/5ec64064-5fbc-11e6-917d-e8673c8faebf.png)

Please add a placeholder somewhere where we can add the title of that page.
# Sub-report

Sub-reports are missing filter information.  Examples:
### Quality Assurance Jobs in IT

![image](https://cloud.githubusercontent.com/assets/504505/17601382/b9535a26-5fbc-11e6-8d81-584197edfc37.png)
### Quality Assurance Jobs in Software

![image](https://cloud.githubusercontent.com/assets/504505/17601373/b19470ea-5fbc-11e6-9088-7b643824f8a4.png)

Both sub-reports shown above are for `Quality Assurance` jobs, but it's to tell that one is for `IT` and the other is for `Software`.

Can you please create placeholders where we can add this information?

CC: @LoganHollins

**Comment by lysodesigns** [comment]
@johnnyoshika Ran out of time today - will wrap this tomorrow.

@LoganHollins Could you provide a list of all the type of job names? Software, IT, etc - that would show up in this position. Thanks!

**Comment by LoganHollins** [comment]
@lysodesigns There is only two report types `Software` & `IT`.

**Comment by johnnyoshika** [comment]
> @johnnyoshika Ran out of time today - will wrap this tomorrow.

@lysodesigns OK, thank you!

**Comment by lysodesigns** [comment]
@johnnyoshika  I added the job type to the "Open" and "New" titles. Can you check out the `jobs-labels` branch and let me know what you think?

@LoganHollins Can't seem to access the subreports. Can you remind me how to achieve this?

**Comment by johnnyoshika** [comment]
@lysodesigns To access subreports, you need to log in.  Once you do, hyperlinks will appears that will direct you to subreports.

I can't seem to run the `jobs-labels` branch at the moment.  Can you please send me a screenshot of your change?  Thanks!

**Comment by lysodesigns** [comment]
@johnnyoshika 
![screen shot 2016-08-26 at 8 13 20 am](https://cloud.githubusercontent.com/assets/6710167/18010350/ffca2e5e-6b64-11e6-9c1a-935953afcf21.png)

**Comment by lysodesigns** [comment]
@LoganHollins @johnnyoshika My lou@email.com login credentials don't work when I run `ember server --proxy htt//analytics.bcjobs.ca` and when I run `ember s` it works, but the main page doesn't load anything except the background

**Comment by johnnyoshika** [comment]
@lysodesigns Looking at the screenshot, I'm concerned that we're only adding titles for the top 2 summary reports and those titles disappear on narrow screens.  The title actually applies to the whole page.  Given that, do you think we should put a large title at the top of the page that indicates that it applies to everything you see on the page?  Or do you think the mock-up you came up with is enough?

**Comment by lysodesigns** [comment]
@johnnyoshika I may have gone overboard with this, but let me know what you think:
![screen shot 2016-08-30 at 8 53 15 pm](https://cloud.githubusercontent.com/assets/6710167/18115457/5399d402-6ef4-11e6-8fbd-ff846f06bb43.png)
![screen shot 2016-08-30 at 8 56 00 pm](https://cloud.githubusercontent.com/assets/6710167/18115455/5396dbd0-6ef4-11e6-94dc-a721a5788163.png)
![screen shot 2016-08-30 at 8 56 12 pm](https://cloud.githubusercontent.com/assets/6710167/18115456/5397bf8c-6ef4-11e6-8dc5-27874c0cfec3.png)

**Comment by johnnyoshika** [comment]
@lysodesigns looks good to me.
