### ISSUE TITLE
"By previous day new jobs"

### ISSUE THREAD

**Issue by ryanstgermaine** [bcjobs/analytics-dashboard#9]
This section under the employers should be "By current day new jobs" and it should show the companies from the date on the date selector, not the previous days. 
![previous_day](https://cloud.githubusercontent.com/assets/6778782/11553092/423b99a0-9940-11e5-9e9e-62ec2dd03382.png)

**Comment by johnnyoshika** [comment]
Change `byPreviousDayNewJobs` to `byNewJobs` and the data should reflect the selected date instead of previous date.

**Comment by johnnyoshika** [comment]
For deployment, all of these 3 things need to happen at the same time:
- Jakub deploys update to Ember
- reset all caches
- deploy analytics changes
