### ISSUE TITLE
Trends report filter drop-down

### ISSUE THREAD

**Issue by johnnyoshika** [bcjobs/analytics-dashboard#92]
Related to: https://github.com/bcjobs/analytics/issues/276
### Background

We are adding a sector and sub-sector filter to the trends report (e.g. http://analytics.bcjobs.ca/, http://analytics.bcjobs.ca/it-jobs/) so that users can drill-down to see data for just the selected sector.
### Requirement

Add a filter selector (e.g. drop-down?) where we'll list sectors and sub-sectors that the user can select.

CC: @LoganHollins

**Comment by lysodesigns** [comment]
@johnnyoshika Can you remind me - did you want this in the header area next to the other filter option?

**Comment by lysodesigns** [comment]
@LoganHollins I added an input field as a place holder. Do we have any dropdowns right now on the site that we can copy to here?

Note: branch `dropdown-filter` will cause conflicts when merged.

**Comment by LoganHollins** [comment]
@lysodesigns The only dropdown we have is in the admin section.
![image](https://cloud.githubusercontent.com/assets/6888104/17725141/5e8a8a0c-63fd-11e6-819a-f83510dfe3f0.png)

**Comment by lysodesigns** [comment]
@LoganHollins I was doing my best to build something in, but I had the feeling it would be replaced by whatever setup you were introducing. Could you possibly add in your dropdown there, and I can make style adjustments afterward?

**Comment by LoganHollins** [comment]
@lysodesigns I have created a dropdown on the `subsector-sector` branch.  The dropdown is populated with the proper data.  The dropdown items currently might not work properly, but it has the proper implementation.  

![image](https://cloud.githubusercontent.com/assets/6888104/17875444/1bbaeb02-6887-11e6-89db-b0ae4c4d80c1.png)

I have also added two custom entries to the dropdown to break the dropdown into sections.

**Comment by LoganHollins** [comment]
@lysodesigns I have updated the `subsector-sector` branch & it is going to be merged into master so we can show the client the functionality. 
https://github.com/bcjobs/analytics-dashboard/pull/94

We changed the design of the drop down a bit, instead of having two sections (Sector/SubSector) we now have each sector followed by its related subsector (in grey).

**Comment by lysodesigns** [comment]
@LoganHollins Styled the dropdowns in `dropdown-clean` branch

**Comment by lysodesigns** [comment]
@LoganHollins I accidentally created this branch off of master instead of dev... would it still be okay to set a pull request to master?

**Comment by LoganHollins** [comment]
@lysodesigns Master & dev are at the same commit, so you can still create the pull request onto dev.

**Comment by lysodesigns** [comment]
@LoganHollins I didn't add a "fixes" label to my commit. Can I confirm this is live before closing?

**Comment by LoganHollins** [comment]
@lysodesigns It is live now.
